apiVersion: batch/v1
kind: Job
metadata:
  name: sleeper
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never